export const CREATE_CAMPAIGN_REQUEST = "CREATE_CAMPAIGN_REQUEST";
export const CREATE_CAMPAIGN_SUCCESS = "CREATE_CAMPAIGN_SUCCESS";
export const CREATE_CAMPAIGN_FAIL = "CREATE_CAMPAIGN_FAIL";

export const CAMPAIGN_LIST_REQUEST = "CAMPAIGN_LIST_REQUEST";
export const CAMPAIGN_LIST_SUCCESS = "CAMPAIGN_LIST_SUCCESS";
export const CAMPAIGN_LIST_FAIL = "CAMPAIGN_LIST_FAIL";

export const CAMPAIGN_LIST_BY_SCREENID_REQUEST =
  "CAMPAIGN_LIST_BY_SCREENID_REQUEST";
export const CAMPAIGN_LIST_BY_SCREENID_SUCCESS =
  "CAMPAIGN_LIST_BY_SCREENID_SUCCESS";
export const CAMPAIGN_LIST_BY_SCREENID_FAIL = "CAMPAIGN_LIST_BY_SCREENID_FAIL";

export const CAMPAIGN_DETAILS_REQUEST = "CAMPAIGN_DETAILS_REQUEST";
export const CAMPAIGN_DETAILS_SUCCESS = "CAMPAIGN_DETAILS_SUCCESS";
export const CAMPAIGN_DETAILS_FAIL = "CAMPAIGN_DETAILS_FAIL";
