export const GET_SINGLE_CREDIT_LOG_REQUEST = "GET_SINGLE_CREDIT_LOG_REQUEST";
export const GET_SINGLE_CREDIT_LOG_SUCCESS = "GET_SINGLE_CREDIT_LOG_SUCCESS";
export const GET_SINGLE_CREDIT_LOG_FAIL = "GET_SINGLE_CREDIT_LOG_FAIL";
