export const WALLET_CREATE_REQUEST = "WALLET_CREATE_REQUEST";
export const WALLET_CREATE_SUCCESS = "WALLET_CREATE_SUCCESS";
export const WALLET_CREATE_FAIL = "WALLET_CREATE_FAIL";

export const WALLET_CREATE_RESET = "WALLET_CREATE_RESET";

export const WALLET_EDIT_REQUEST = "WALLET_EDIT_REQUEST";
export const WALLET_EDIT_SUCCESS = "WALLET_EDIT_SUCCESS";
export const WALLET_EDIT_FAIL = "WALLET_EDIT_FAIL";

export const WALLET_EDIT_RESET = "WALLET_EDIT_RESET";

export const GET_WALLET_DATA_REQUEST = "GET_WALLET_DATA_REQUEST";
export const GET_WALLET_DATA_SUCCESS = "GET_WALLET_DATA_SUCCESS";
export const GET_WALLET_DATA_ERROR = "GET_WALLET_DATA_ERROR";

export const GET_TRANJECTION_DATA_REQUEST = "GET_TRANJECTION_DATA_REQUEST";
export const GET_TRANJECTION_DATA_SUCCESS = "GET_TRANJECTION_DATA_SUCCESS";
export const GET_TRANJECTION_DATA_ERROR = "GET_TRANJECTION_DATA_ERROR,";
